### ISSUE TITLE
Should have a license

### ISSUE THREAD

**Issue by kov** [McCrearyD/Chrome_Controller#32]
I know you want the extension to be Open Source but, since it does not have a license, using it as an open source project is tricky. Would you mind adding a license to the repository?

A very simple license that you could use is the 3-clause BSD license that is used by Chromium, for instance.

https://opensource.org/licenses/BSD-3-Clause

**Comment by verbiiz** [comment]
For sure! I will add one asap. Thanks for pointing this out :)

**Comment by kov** [comment]
Hey there! Any progress on this? We are considering using your code on something we are working on, but we'd need the license for that =)

**Comment by verbiiz** [comment]
So sorry for the long wait, I'm putting one up right now!
